### ISSUE TITLE
fsbench and thus subd can't handle ZFS filesystems

### ISSUE THREAD

**Issue by nshalman** [Cloud-Foundations/Dominator#29]
Expected behavior:
 * Invoke `subd`
 * `subd` starts

Actual behavior:
 * Invoke `subd`
 * `subd` can't find the device path for the filesystem and refuses to start.

Sample error message:
```
# ./subd -certFile ./subd.pem -keyFile ./subd.key.pem -alsoLogToStderr -initialLogDebugLevel 100 -subdDir .subd -rootDir /
Mounted tmpfs on: /.subd/tmp
Unable to measure read speed: unable to find device path for: /.subd/root
```

Some different ways of looking at the root filesystem in question:
```
# df -h /
Filesystem         Size  Used Avail Use% Mounted on
rpool/ROOT/buster   76G  758M   76G   1% /
# mount | grep ROOT
rpool/ROOT/buster on / type zfs (rw,relatime,xattr,noacl)
# zfs list rpool/ROOT/buster
NAME                USED  AVAIL     REFER  MOUNTPOINT
rpool/ROOT/buster   758M  75.0G      758M  /
```

This zpool happens to be on a single block device:
```
# zpool status rpool
  pool: rpool
 state: ONLINE
config:

        NAME        STATE     READ WRITE CKSUM
        rpool       ONLINE       0     0     0
          vda1      ONLINE       0     0     0

errors: No known data errors
```

It should be noted, however, that ZFS supports other disk configurations too.

Of course, for entertainment purposes (not an acceptable workaround), when given an ext4 filesystem formatted on top of a zvol, subd is satisfied:

```
# zfs list -t volume
NAME            USED  AVAIL     REFER  MOUNTPOINT
rpool/testvol  20.6G  95.6G     2.50M  -

# ls -l /dev/zvol/rpool/testvol
lrwxrwxrwx 1 root root 9 Dec 11 18:46 /dev/zvol/rpool/testvol -> ../../zd0

# mount | grep ext4
/dev/zd0 on /var/cache/subd-test type ext4 (rw,relatime,stripe=2)

# df -h /var/cache/subd-test/
Filesystem      Size  Used Avail Use% Mounted on
/dev/zd0         20G   45M   19G   1% /var/cache/subd-test

# ./subd -certFile ./subd.pem -keyFile ./subd.key.pem -alsoLogToStderr -initialLogDebugLevel 100 -subdDir .subd -rootDir /var/cache/subd-test
Mounted tmpfs on: /var/cache/subd-test/.subd/tmp
2019/12/11 18:47:24 Restoring CPU limit: 50% 
2019/12/11 18:47:53 reverse listener: remember(redacted): 0xc000010008
2019/12/11 18:58:37 reverse listener: forget(redacted)
```

**Comment by rgooch** [comment]
I don't think there is a simple, clean solution for this, particularly if there isn't a direct mapping from file-system to block device. I see three main solutions:
1) Short term: add a command-line flag to `subd` which allows you to specify the speed instead
2) Short term: hard-code a default speed if the detection fails (perhaps 50 MB/s, a slow HDD)
2) Long term: build speed detection into the scanning code, starting at maximum speed.

**Comment by nshalman** [comment]
> I don't think there is a simple, clean solution for this, particularly if there isn't a direct mapping from file-system to block device. I see three main solutions:
> 
> 1. Short term: add a command-line flag to `subd` which allows you to specify the speed instead
> 2. Short term: hard-code a default speed if the detection fails (perhaps 50 MB/s, a slow HDD)
> 3. Long term: build speed detection into the scanning code, starting at maximum speed.

If you have time to implement any of those solutions it would be greatly appreciated, but I understand that it's unlikely a high priority for you at this time. In the meantime I will see if I can grok the code well enough to take a pass at 1 or 2 in a way that doesn't dirty up the codebase (I'm still relatively new to golang so it will likely take me a while.)

But a quick question: What is the significance of the speed setting used by the scanning code?

With that much filesystem activity ZFS is going to be pretty aggressive about caching metadata and even data into RAM which will make it go faster than the underlying block device(s) anyway. I wouldn't know what speed I'd want to provide for option 1.

Thanks for your time (and for Dominator)!

**Comment by rgooch** [comment]
I've implemented (1) in PR# 34. Please pull that commit or use my fork and test that this works for you. You need to specify at least `-rootDeviceBytesPerSecond=1MiB`.

The reason for the code to measure the speed is because `subd` rate limits it's I/O so that it does not impact normal workloads. Even if you have plenty of RAM to cache the entire file-system, you may not want to do that, because it might mean that there is less RAM for caching more important file-systems (such as where application data lie).

If you're unsure what values to give, I suggest:
- HDD: `50MiB`
- SSD: `500MiB`

**Comment by nshalman** [comment]
Initial testing looks like that works. Thank you!!

**Comment by rgooch** [comment]
Great. Good enough to close this issue?

**Comment by nshalman** [comment]
Good enough for me for now, certainly.

I do think implementing that third option some day would be very nice, but up to you if/how you want to keep track of that idea...
> 3. Long term: build speed detection into the scanning code, starting at maximum speed.

Thanks again!
