### ISSUE TITLE
Enable computed-files inheritance

### ISSUE THREAD

**Issue by michaeljs1990** [Cloud-Foundations/Dominator#39]
Currently if your SourceImage has computed-files specified they are not passed on to the current building image. An example use case could be for generating your /etc/hostname or /etc/motd file dynamically.

It seems like computed-files would be propagated and just a single computed-files would suffice or should the same convention be followed to give users the ability to add or override computed files via `computed-files` and `computed-files.add`. 

From @rgooch on slack

> Indeed, following the same pattern as filters and triggers would give the most flexibility. You then get three possibilities: 
> 
> 1) no computed files (replaced with zero-length regular files);
> 2) specify a new set of computed files (existing computed files that are not listed would be replaced with zero-length regular files);
> 3) add more computed files (changing the Source location for ones that are inherited).
>

**Comment by rgooch** [comment]
PR #56 implements this.
