### ISSUE TITLE
Allow resolv.conf config via files config

### ISSUE THREAD

**Issue by michaeljs1990** [Cloud-Foundations/Dominator#44]
Currently if you want to have your resolv.conf configured during your image build a few unexpected things happen.

1. If you configure resolv.conf with the files folder it will be overwritten right away by the internal copy of resolv.conf from the host system.
2. If you configure resolve.conf in post-install-files it will be overwritten by /dev/null shortly after.

It would be nice if this was only managed in the filters file as this seems to be an exception to that during the image build process. In our case we have an anycast IP that would be nice to control in a single location.

**Comment by rgooch** [comment]
PR #53 resolves (sic) this. Please reopen if this doesn't solve it for you.
