### ISSUE TITLE
Please correct certificate for https://cloud-foundations.org and provide information about the org.

### ISSUE THREAD

**Issue by zmt** [Cloud-Foundations/Dominator#68]
It is apparently hosted at safe-mbox.org:
```
$ dig +nocomment +nostats cloud-foundations.org

; <<>> DiG 9.10.6 <<>> +nocomment +nostats cloud-foundations.org
;; global options: +cmd
;cloud-foundations.org.         IN      A
cloud-foundations.org.  864     IN      A       45.55.5.21
$ dig +nocomment +nostats safe-mbox.com

; <<>> DiG 9.10.6 <<>> +nocomment +nostats safe-mbox.com
;; global options: +cmd
;safe-mbox.com.                 IN      A
safe-mbox.com.          864     IN      A       45.55.5.21
```

![image](https://user-images.githubusercontent.com/290465/81126348-ddef5900-8eef-11ea-8f4d-b3b302122c0d.png)

I wanted to learn more about the organization currently holding the copyright since we only recently learned this repository moved from https://github.com/Symantec/Dominator and updated our dependencies. I found your homepage @rgooch: https://www.safe-mbox.com/~rgooch/

**Comment by zmt** [comment]
Also, it might help your users if you could update the old repo home so they don't have to find their way to this comment to discover the move: https://github.com/Symantec/Dominator/issues/652#issuecomment-557698331

**Comment by rgooch** [comment]
Certificate fixed.
We no longer have access to the old repository.

**Comment by zmt** [comment]
Thank you for fixing the certificate. I hope you have plans to add some more current background info at some point. I partially opened this over concerns about corporate OSS departments vetting this software, so the more current, legitimate info about "Cloud-Foundations" org, the better for your brand. I love the product and I don't want it taken away by some vetting process at my employer.

**Comment by rgooch** [comment]
We've started building out a website: https://www.cloud-foundations.org/
Contributions welcome: https://github.com/Cloud-Foundations/website
